// French | English | Simplified Chinese | Spanish
const rows = `Une source illisible ne peut pas être isolée du cache du compte. Télécharge son original depuis l’accueil avant de sauvegarder.|An unreadable source cannot be separated from the account cache. Download its original from the home screen before backing up.|无法从账户缓存分离不可读来源。备份前请在首页下载原始文件。|No se puede separar una fuente ilegible de la caché de cuenta. Descarga el original desde el inicio antes de guardar.
Sauvegarder et restaurer mes données|Back up and restore my data|备份和恢复我的数据|Guardar y restaurar mis datos
Carnets, documents embarqués, souvenirs et préférences utiles dans un seul fichier vérifié (64 Mo maximum).|Trips, embedded documents, memories and useful preferences in one verified file (64 MB maximum).|旅行、内嵌文档、回忆和常用设置保存到一个校验文件中（最大64 MB）。|Viajes, documentos incluidos, recuerdos y preferencias en un archivo verificado (máximo 64 MB).
Seuls les carnets téléchargés de l’espace ouvert sont sauvegardés. Comptes, droits, ressources externes et caches réseau sont exclus.|Only downloaded trips in the current space are backed up. Accounts, permissions, external resources and network caches are excluded.|仅备份当前空间已下载的旅行。不包括账户、权限、外部资源和网络缓存。|Solo se guardan los viajes descargados del espacio actual. Se excluyen cuentas, permisos, recursos externos y cachés de red.
{count} carnet(s) distant(s) non téléchargé(s).|{count} remote trip(s) not downloaded.|{count}个远程旅行尚未下载。|{count} viaje(s) remoto(s) sin descargar.
Télécharger ma sauvegarde complète|Download my complete backup|下载完整备份|Descargar mi copia completa
Restaurer mes données|Restore my data|恢复我的数据|Restaurar mis datos
Choisir une sauvegarde complète|Choose a complete backup|选择完整备份|Elegir una copia completa
Vérification de la sauvegarde…|Checking backup…|正在检查备份…|Verificando la copia…
Sauvegarde complète téléchargée. Conserve ce fichier hors de cet appareil.|Complete backup downloaded. Keep this file outside this device.|完整备份已下载。请将此文件保存在其他设备上。|Copia completa descargada. Guarda este archivo fuera de este dispositivo.
Restauration terminée dans l’espace local privé. Déconnecte-toi pour retrouver ces carnets.|Restoration completed in the private local space. Sign out to find these trips.|已恢复到本地私人空间。退出登录后可查看这些旅行。|Restauración completada en el espacio local privado. Cierra la sesión para ver estos viajes.
Restauration terminée. Tes carnets et souvenirs sont disponibles ici.|Restoration completed. Your trips and memories are available here.|恢复完成。旅行和回忆已可使用。|Restauración completada. Tus viajes y recuerdos están disponibles aquí.
Restauration incomplète : certains éléments peuvent déjà être visibles. Le fichier original et les données existantes sont conservés.|Restoration incomplete: some items may already be visible. The original file and existing data are preserved.|恢复未完成：部分内容可能已显示。原文件和已有数据均已保留。|Restauración incompleta: algunos elementos pueden estar visibles. Se conservan el archivo original y los datos existentes.
Reprendre la restauration|Resume restoration|继续恢复|Continuar la restauración
Pour reprendre, sélectionne le même fichier de sauvegarde.|To resume, select the same backup file.|请选择同一备份文件以继续恢复。|Para continuar, selecciona el mismo archivo de copia.
{count} source(s) brute(s) conservée(s) séparément.|{count} raw source(s) preserved separately.|已单独保留{count}个原始来源。|{count} fuente(s) original(es) conservada(s) por separado.
Télécharger la source {count}|Download source {count}|下载来源{count}|Descargar la fuente {count}
Bilan de restauration|Restoration preview|恢复预览|Resumen de restauración
La restauration crée des carnets privés sur cet appareil. Les carnets existants et les droits serveur restent conservés.|Restoration creates private trips on this device. Existing trips and server permissions are preserved.|恢复将在本设备创建私人旅行。已有旅行和服务器权限保持不变。|La restauración crea viajes privados en este dispositivo. Se conservan los viajes existentes y los permisos del servidor.
{count} carnet(s) à retrouver.|{count} trip(s) to restore.|将恢复{count}个旅行。|{count} viaje(s) para recuperar.
{count} souvenir(s) à retrouver.|{count} memory/memories to restore.|将恢复{count}条回忆。|{count} recuerdo(s) para recuperar.
{count} collision(s) traitée(s) sans remplacer les carnets.|{count} collision(s) handled without replacing trips.|处理{count}项冲突，不替换已有旅行。|{count} coincidencia(s) tratada(s) sin sustituir viajes.
{count} préférence(s) existante(s) conservée(s).|{count} existing preference(s) kept.|保留{count}项已有设置。|{count} preferencia(s) existente(s) conservada(s).
Espace supplémentaire estimé : {count} Mo, journal compris. Le quota réel du navigateur sera vérifié lors des écritures.|Estimated additional space: {count} MB, including the journal. The actual browser quota is checked when writing.|预计额外空间：{count} MB（含恢复日志）。写入时将检查浏览器实际配额。|Espacio adicional estimado: {count} MB, incluido el registro. La cuota real del navegador se comprueba al escribir.
Ce fichier historique contient uniquement des carnets. Souvenirs et préférences ne sont pas inclus.|This older file contains trips only. Memories and preferences are not included.|此旧版文件仅包含旅行，不包含回忆和设置。|Este archivo antiguo solo contiene viajes. No incluye recuerdos ni preferencias.
Une interruption peut laisser une restauration partielle. Reprendre le même fichier conserve les identités et évite les doublons.|An interruption may leave a partial restoration. Resuming the same file preserves identities and avoids duplicates.|中断可能导致部分恢复。继续恢复同一文件将保留标识并避免重复。|Una interrupción puede dejar una restauración parcial. Continuar con el mismo archivo conserva los identificadores y evita duplicados.
Confirmer la restauration|Confirm restoration|确认恢复|Confirmar restauración
La sauvegarde dépasse la limite de 64 Mo. Aucun fichier incomplet n’est téléchargé.|The backup exceeds 64 MB. No incomplete file is downloaded.|备份超过64 MB。未下载不完整文件。|La copia supera 64 MB. No se descarga un archivo incompleto.
Les anciens fichiers restent limités à 5 Mo. Crée une sauvegarde complète depuis leur navigateur d’origine.|Older files remain limited to 5 MB. Create a complete backup in their original browser.|旧版文件仍限5 MB。请在原浏览器创建完整备份。|Los archivos antiguos siguen limitados a 5 MB. Crea una copia completa desde su navegador original.
Le contrôle d’intégrité a échoué. Le fichier et tes données restent conservés.|Integrity check failed. The file and your data are preserved.|完整性校验失败。文件和数据均已保留。|Falló la verificación de integridad. Se conservan el archivo y tus datos.
La sauvegarde est invalide. Aucune restauration n’a commencé.|Invalid backup. No restoration has started.|备份无效。尚未开始恢复。|Copia inválida. No se ha iniciado la restauración.
Les souvenirs existants sont illisibles. Télécharge leur source avant de restaurer.|Existing memories cannot be read. Download their source before restoring.|已有回忆无法读取。恢复前请下载原始来源。|Los recuerdos existentes no se pueden leer. Descarga su fuente antes de restaurar.
Des données ont changé depuis le bilan. La restauration est arrêtée pour les préserver.|Data changed since the preview. Restoration stopped to preserve it.|预览后数据已更改。恢复已停止以保护数据。|Los datos cambiaron después del resumen. La restauración se detuvo para conservarlos.
Termine la restauration en attente avant d’en commencer une autre.|Finish the pending restoration before starting another.|请先完成待恢复操作，再开始另一项。|Termina la restauración pendiente antes de empezar otra.
Cette sauvegarde a déjà été restaurée ici. Aucun doublon n’a été ajouté.|This backup has already been restored here. No duplicates were added.|此备份已在此处恢复。未添加重复内容。|Esta copia ya se restauró aquí. No se añadieron duplicados.
Le journal de restauration est illisible ou indisponible. Sa source est conservée.|The restoration journal cannot be read or is unavailable. Its source is preserved.|恢复日志无法读取或不可用。原始来源已保留。|El registro de restauración no se puede leer o no está disponible. Se conserva su fuente.
Une écriture n’a pas pu être relue. Réessaie la restauration avec le même fichier.|A write could not be read back. Retry restoration with the same file.|写入后无法重新读取。请使用同一文件重试恢复。|No se pudo releer una escritura. Reintenta con el mismo archivo.
Le stockage est indisponible ou plein. Des éléments peuvent déjà être restaurés ; conserve le fichier et reprends la même restauration.|Storage is unavailable or full. Some items may already be restored; keep the file and resume the same restoration.|存储不可用或已满。部分内容可能已恢复；请保留文件并继续同一次恢复。|El almacenamiento no está disponible o está lleno. Algunos elementos pueden haberse restaurado; conserva el archivo y continúa la misma restauración.`;
export function backupDictionary(index: number): Record<string, string> {
  return Object.fromEntries(rows.split('\n').map(row => { const parts = row.split('|'); return [parts[0], parts[index + 1]]; }));
}
